CREATE TABLE IF NOT EXISTS "PlannedMatch" (
  "id" SERIAL PRIMARY KEY,
  "sportId" INTEGER NOT NULL,
  "sportName" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'scheduled',
  "venue" TEXT NOT NULL,
  "startTime" TIMESTAMP(3),
  "endTime" TIMESTAMP(3),
  "durationMinutes" INTEGER NOT NULL DEFAULT 60,
  "dalAId" INTEGER NOT NULL,
  "dalBId" INTEGER NOT NULL,
  "matchRound" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PlannedMatch_dalAId_fkey" FOREIGN KEY ("dalAId") REFERENCES "Mandal"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "PlannedMatch_dalBId_fkey" FOREIGN KEY ("dalBId") REFERENCES "Mandal"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
